/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import db.dadosFuncionario;
import model.funcionario;

/**
 *
 * @author gbarrosn
 */
public class cadastrarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form cadastrarFuncionario
     */
    public cadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDataAdmissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBoxEntrada = new javax.swing.JComboBox<>();
        jComboBoxSaida = new javax.swing.JComboBox<>();
        jComboBoxSemanal = new javax.swing.JComboBox<>();
        jComboBoxSetor = new javax.swing.JComboBox<>();
        jComboBoxEscala = new javax.swing.JComboBox<>();
        jComboBoxFuncao = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/GovPERGBpequeno1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 203, 113));

        jButton1.setText("Tela Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 393, 114, 27));
        jPanel1.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 317, -1));

        jLabel2.setText("Nome completo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, -1, -1));

        jLabel3.setText("Matrícula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 131, -1, -1));

        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 156, 112, -1));

        jLabel4.setText("Setor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 193, -1, -1));

        jLabel5.setText("Turno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 193, -1, -1));

        jLabel6.setText("Função:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 193, -1, -1));

        jLabel7.setText("Data de admissão:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 255, -1, -1));
        jPanel1.add(jTextFieldDataAdmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 280, 162, -1));

        jLabel8.setText("Escala:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 255, -1, -1));

        jLabel9.setText("Horario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 255, -1, -1));

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde" }));
        jPanel1.add(jComboBoxTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 218, 149, -1));

        jLabel10.setText("Horas semanais:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 317, -1, -1));

        jLabel11.setText("Código de barras:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 317, -1, -1));
        jPanel1.add(jTextFieldCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 342, 223, -1));

        jLabel12.setText("Senha:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 317, -1, -1));

        jTextFieldSenha.setText("sad@123");
        jPanel1.add(jTextFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 342, 149, -1));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 393, 108, 27));

        jCheckBox2.setText("Coordenação");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 157, -1, -1));

        jComboBoxEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        jPanel1.add(jComboBoxEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 280, 114, -1));

        jComboBoxSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jPanel1.add(jComboBoxSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 280, 103, -1));

        jComboBoxSemanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "40", "44" }));
        jPanel1.add(jComboBoxSemanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, 162, -1));

        jComboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RH", "Procon", "Funape", "CAS", "Coordenação", "Compesa", "SDS", "Detran", "Limpeza", "TI" }));
        jPanel1.add(jComboBoxSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, 162, -1));

        jComboBoxEscala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seg. - Sab.", "Seg. - Sex." }));
        jPanel1.add(jComboBoxEscala, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 280, 149, -1));

        jComboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assistente Administrativo", "RH", "Procon", "Funape", "CAS", "Coordenação", "Compesa", "SDS", "Detran", "Limpeza", "TI" }));
        jPanel1.add(jComboBoxFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 218, 223, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        telaInicial tela = new telaInicial();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:


        String nome = jTextFieldNome.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo nome é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int matricula = 0;
        String matriculaStr = jTextFieldMatricula.getText().trim();
        if (matriculaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo matrícula é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                matricula = Integer.parseInt(matriculaStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "O campo matrícula deve ser um número", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String setor = jComboBoxSetor.getSelectedItem().toString();
        if (setor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo setor é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String turno = jComboBoxTurno.getSelectedItem().toString();
        if (turno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo turno é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String funcao = jComboBoxFuncao.getSelectedItem().toString();
        if (funcao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo função é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String dataAdmissao = jTextFieldDataAdmissao.getText().trim();
        if (dataAdmissao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo data de admissão é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String escala = jComboBoxEscala.getSelectedItem().toString();
        if (escala.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo escala é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String horario = jComboBoxEntrada.getSelectedItem().toString() + " - " + jComboBoxSaida.getSelectedItem().toString();
        if (horario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo horário é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String horasSemanais = jComboBoxSemanal.getSelectedItem().toString();
        if (horasSemanais.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo horas semanais é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String codigoDeBarras = jTextFieldCodigoBarras.getText().trim();
        if (codigoDeBarras.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo código de barras é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String senha = jTextFieldSenha.getText().trim();
        if (senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo senha é obrigatório", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean adm = jCheckBox2.isSelected();

        funcionario novoFuncionario = new funcionario();
        novoFuncionario.setNome(nome);
        novoFuncionario.setMatricula(matricula);
        novoFuncionario.setSetor(setor);
        novoFuncionario.setTurno(turno);
        novoFuncionario.setFuncao(funcao);
        novoFuncionario.setDataAdmissao(dataAdmissao);
        novoFuncionario.setEscala(escala);
        novoFuncionario.setHorario(horario);
        novoFuncionario.setHorasSemanais(horasSemanais);
        novoFuncionario.setCodigoDeBarras(codigoDeBarras);
        novoFuncionario.setSenha(senha);
        novoFuncionario.setAdm(adm);


        try {
        dadosFuncionario.cadastrarFuncionario(novoFuncionario);
        JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        cadastrarFuncionario tela = new cadastrarFuncionario();
        tela.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o funcionário: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBoxEntrada;
    private javax.swing.JComboBox<String> jComboBoxEscala;
    private javax.swing.JComboBox<String> jComboBoxFuncao;
    private javax.swing.JComboBox<String> jComboBoxSaida;
    private javax.swing.JComboBox<String> jComboBoxSemanal;
    private javax.swing.JComboBox<String> jComboBoxSetor;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodigoBarras;
    private javax.swing.JTextField jTextFieldDataAdmissao;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
